#!/usr/bin/env bash
# Generate agent prompt files from templates using config.yaml
#
# Usage: ./scripts/generate-agent-prompts.sh
#
# This script reads docs/prompts/config.yaml and generates prompt files
# from templates in docs/prompts/templates/

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/docs/prompts/config.yaml"
TEMPLATE_DIR="$PROJECT_ROOT/docs/prompts/templates"
OUTPUT_DIR="$PROJECT_ROOT/docs/prompts"

echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Agent Prompt Generator${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo ""

# Check dependencies
if ! command -v yq &> /dev/null; then
    echo -e "${RED}ERROR: yq is not installed${NC}"
    echo ""
    echo "Install with:"
    echo "  Ubuntu/Debian: sudo snap install yq"
    echo "  macOS: brew install yq"
    echo "  Or download from: https://github.com/mikefarah/yq/releases"
    echo ""
    exit 1
fi

# Check files exist
if [ ! -f "$CONFIG_FILE" ]; then
    echo -e "${RED}ERROR: Configuration file not found: $CONFIG_FILE${NC}"
    exit 1
fi

if [ ! -d "$TEMPLATE_DIR" ]; then
    echo -e "${RED}ERROR: Template directory not found: $TEMPLATE_DIR${NC}"
    exit 1
fi

echo "📋 Reading configuration from: $CONFIG_FILE"
echo ""

# Extract values from YAML using yq
COMPONENT_NAME=$(yq '.component.name' "$CONFIG_FILE")
COMPONENT_TYPE=$(yq '.component.type' "$CONFIG_FILE")
SPECIFICATION=$(yq '.paths.specification' "$CONFIG_FILE")
MASTER_PLAN=$(yq '.paths.master_plan' "$CONFIG_FILE")
DETAILED_PLAN=$(yq '.paths.detailed_plan' "$CONFIG_FILE")
OUTPUT_PLAN=$(yq '.paths.output_plan' "$CONFIG_FILE")
OUTPUT_REVIEW=$(yq '.paths.output_review' "$CONFIG_FILE")
OUTPUT_TEST_REPORT=$(yq '.paths.output_test_report' "$CONFIG_FILE")
GITHUB_PR=$(yq '.github.pr' "$CONFIG_FILE")
GITHUB_ISSUE=$(yq '.github.issue' "$CONFIG_FILE")
GIT_BRANCH=$(yq '.github.branch' "$CONFIG_FILE")
REQUIRES_OAUTH=$(yq '.context.requires_oauth' "$CONFIG_FILE")
REQUIRES_KEYCLOAK=$(yq '.context.requires_keycloak' "$CONFIG_FILE")
SECURITY_CRITICAL=$(yq '.context.security_critical' "$CONFIG_FILE")
MODEL_TECH_ARCH=$(yq '.models.technical_architect' "$CONFIG_FILE")
MODEL_PLAN=$(yq '.models.feature_implementer_plan' "$CONFIG_FILE")
MODEL_IMPL=$(yq '.models.feature_implementer' "$CONFIG_FILE")
MODEL_TEST=$(yq '.models.test_suite_generator' "$CONFIG_FILE")
MODEL_REVIEW=$(yq '.models.code_security_reviewer' "$CONFIG_FILE")
MASTER_PLAN_SECTIONS=$(yq '.plan_mode.master_plan_sections' "$CONFIG_FILE")

# Display current configuration
echo -e "${YELLOW}Component:${NC} $COMPONENT_NAME"
echo -e "${YELLOW}Type:${NC} $COMPONENT_TYPE"
echo -e "${YELLOW}GitHub PR:${NC} $GITHUB_PR"
echo -e "${YELLOW}Branch:${NC} $GIT_BRANCH"
echo ""

# Get current timestamp
GENERATION_TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Function to generate header for generated files
generate_header() {
    local template_name="$1"
    cat <<EOF
<!--
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠️  GENERATED FILE - DO NOT EDIT DIRECTLY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This file is automatically generated from:
  Template: docs/prompts/templates/${template_name}
  Config:   docs/prompts/config.yaml

To modify this prompt:
  1. Edit docs/prompts/config.yaml
  2. Run ./scripts/generate-agent-prompts.sh

Generated: ${GENERATION_TIMESTAMP}
Component: ${COMPONENT_NAME}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-->

EOF
}

# Function to process conditional blocks
# Evaluates {{#if condition}}...{{#endif}} blocks based on boolean config values
process_conditionals() {
    local content="$1"
    local result=""

    # Process requires_oauth_context conditionals
    if [ "$REQUIRES_OAUTH" = "true" ]; then
        # Include content, remove conditional markers
        result=$(echo "$content" | sed '/{{#if requires_oauth_context}}/,/{{#endif requires_oauth_context}}/{ /{{#if requires_oauth_context}}/d; /{{#endif requires_oauth_context}}/d; }')
    else
        # Remove entire conditional block
        result=$(echo "$content" | sed '/{{#if requires_oauth_context}}/,/{{#endif requires_oauth_context}}/d')
    fi
    content="$result"

    # Process requires_keycloak_context conditionals
    if [ "$REQUIRES_KEYCLOAK" = "true" ]; then
        result=$(echo "$content" | sed '/{{#if requires_keycloak_context}}/,/{{#endif requires_keycloak_context}}/{ /{{#if requires_keycloak_context}}/d; /{{#endif requires_keycloak_context}}/d; }')
    else
        result=$(echo "$content" | sed '/{{#if requires_keycloak_context}}/,/{{#endif requires_keycloak_context}}/d')
    fi
    content="$result"

    # Process security_critical conditionals
    if [ "$SECURITY_CRITICAL" = "true" ]; then
        result=$(echo "$content" | sed '/{{#if security_critical}}/,/{{#endif security_critical}}/{ /{{#if security_critical}}/d; /{{#endif security_critical}}/d; }')
    else
        result=$(echo "$content" | sed '/{{#if security_critical}}/,/{{#endif security_critical}}/d')
    fi

    echo "$result"
}

# Function to escape special characters for sed replacement
# In sed, & and \ have special meaning in replacement strings
escape_sed_replacement() {
    echo "$1" | sed 's/[&/\]/\\&/g'
}

# Function to generate a prompt from template
generate_prompt() {
    local template_file="$1"
    local output_file="$2"
    local description="$3"
    local model_var="$4"
    local template_name="$(basename "$template_file")"

    if [ ! -f "$template_file" ]; then
        echo -e "${RED}✗ Template not found: $template_file${NC}"
        return 1
    fi

    echo -n "  Generating $description... "

    # Read template content
    local template_content
    template_content=$(cat "$template_file")

    # Process conditional blocks first
    template_content=$(process_conditionals "$template_content")

    # Escape special characters in replacement values for sed
    local component_name_escaped=$(escape_sed_replacement "$COMPONENT_NAME")
    local component_type_escaped=$(escape_sed_replacement "$COMPONENT_TYPE")
    local specification_escaped=$(escape_sed_replacement "$SPECIFICATION")
    local master_plan_escaped=$(escape_sed_replacement "$MASTER_PLAN")
    local detailed_plan_escaped=$(escape_sed_replacement "$DETAILED_PLAN")
    local output_plan_escaped=$(escape_sed_replacement "$OUTPUT_PLAN")
    local output_review_escaped=$(escape_sed_replacement "$OUTPUT_REVIEW")
    local output_test_report_escaped=$(escape_sed_replacement "$OUTPUT_TEST_REPORT")
    local github_pr_escaped=$(escape_sed_replacement "$GITHUB_PR")
    local github_issue_escaped=$(escape_sed_replacement "$GITHUB_ISSUE")
    local git_branch_escaped=$(escape_sed_replacement "$GIT_BRANCH")
    local model_var_escaped=$(escape_sed_replacement "$model_var")
    local master_plan_sections_escaped=$(escape_sed_replacement "$MASTER_PLAN_SECTIONS")

    # Generate header and content, then write to output
    {
        generate_header "$template_name"
        echo "$template_content" | sed \
            -e "s|{{component_name}}|$component_name_escaped|g" \
            -e "s|{{component_type}}|$component_type_escaped|g" \
            -e "s|{{specification}}|$specification_escaped|g" \
            -e "s|{{master_plan}}|$master_plan_escaped|g" \
            -e "s|{{detailed_plan}}|$detailed_plan_escaped|g" \
            -e "s|{{output_plan}}|$output_plan_escaped|g" \
            -e "s|{{output_review}}|$output_review_escaped|g" \
            -e "s|{{output_report}}|$output_test_report_escaped|g" \
            -e "s|{{github_pr}}|$github_pr_escaped|g" \
            -e "s|{{github_issue}}|$github_issue_escaped|g" \
            -e "s|{{git_branch}}|$git_branch_escaped|g" \
            -e "s|{{model}}|$model_var_escaped|g" \
            -e "s|{{master_plan_sections}}|$master_plan_sections_escaped|g"
    } > "$output_file"

    echo -e "${GREEN}✓${NC}"
}

# Generate all prompts
echo "🔨 Generating prompt files:"
echo ""

generate_prompt \
    "$TEMPLATE_DIR/agent-technical-architect.md.template" \
    "$OUTPUT_DIR/agent-technical-architect.md" \
    "technical-architect prompt" \
    "$MODEL_TECH_ARCH"

generate_prompt \
    "$TEMPLATE_DIR/agent-feature-implementer-plan-mode.md.template" \
    "$OUTPUT_DIR/agent-feature-implementer-plan-mode.md" \
    "feature-implementer-plan-mode prompt" \
    "$MODEL_PLAN"

generate_prompt \
    "$TEMPLATE_DIR/agent-feature-implementer.md.template" \
    "$OUTPUT_DIR/agent-feature-implementer.md" \
    "feature-implementer prompt" \
    "$MODEL_IMPL"

generate_prompt \
    "$TEMPLATE_DIR/agent-test-suite-generator.md.template" \
    "$OUTPUT_DIR/agent-test-suite-generator.md" \
    "test-suite-generator prompt" \
    "$MODEL_TEST"

generate_prompt \
    "$TEMPLATE_DIR/agent-code-security-reviewer.md.template" \
    "$OUTPUT_DIR/agent-code-security-reviewer.md" \
    "code-security-reviewer prompt" \
    "$MODEL_REVIEW"

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✓ Successfully generated 5 agent prompt files${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo ""
echo "Generated files:"
echo "  - docs/prompts/agent-technical-architect.md"
echo "  - docs/prompts/agent-feature-implementer-plan-mode.md"
echo "  - docs/prompts/agent-feature-implementer.md"
echo "  - docs/prompts/agent-test-suite-generator.md"
echo "  - docs/prompts/agent-code-security-reviewer.md"
echo ""
echo -e "${YELLOW}Note: These are generated files. Do not edit directly!${NC}"
echo -e "${YELLOW}      Edit config.yaml and re-run this script instead.${NC}"
echo ""
